### ISSUE TITLE
请问运行时出现cannot find package "mapreduce" 是什么意思？

### ISSUE THREAD

**Issue by suedeyg** [happyer/distributed-computing#11]
不好意思，go语言新手，目前正在研究raft。但是在go run wc.go时不成功，出现上述错误。请问“mapreduce”这个包怎么回事？

**Comment by JustinLi3707** [comment]
你需要看下import的用法，这是go语言的基础

**Comment by suedeyg** [comment]
> 你需要看下import的用法，这是go语言的基础

thx，问题已解决，入门级的问题。
