### ISSUE TITLE
关于Raft 包

### ISSUE THREAD

**Issue by JustinLi3707** [happyer/distributed-computing#12]
你好，看了你的raft部分的实现代码，请问如何使用这个raft包呢？希望有个主程序可以跟着调试一下，更好的弄清整个raft流程，方便指导下写个简单的测试用例吗？非常感谢。

**Comment by happyer** [comment]
里面有一个单测，可以看看
还有一个kv 存储，他也使用了raft的，你可以看一下

**Comment by happyer** [comment]
> 你好，看了你的raft部分的实现代码，请问如何使用这个raft包呢？希望有个主程序可以跟着调试一下，更好的弄清整个raft流程，方便指导下写个简单的测试用例吗？非常感谢。

里面有一个单测，可以看看
还有一个kv 存储，他也使用了raft的，你可以看一下，里面就是他的正确使用场景，当然是简化版的但本质都是一样的
