### ISSUE TITLE
labrpc

### ISSUE THREAD

**Issue by liuxp0827** [happyer/distributed-computing#3]
import "labrpc"
请问下 labrpc是你自己写的包? 
没有这个package, 这个test跑不起来啊

**Comment by happyer** [comment]
肯定的没有这个RPC 肯定跑不起来的，你看看的GO语言的path 有没有正确，如果是正确的CD 进入SRC 然后go test dir
PONPON <notifications@github.com>于2017年2月15日 周三下午3:20写道：

**Comment by liuxp0827** [comment]
我知道,这个labrpc是你本地写的package么?你没有放上仓库,我获取不到

**Comment by happyer** [comment]
本地的package 是什么意思，没有名白

**Comment by liuxp0827** [comment]
import "labrpc"
这个rpc不是官方的package,所以不在GOROOT下,那肯定是在本地的GOPATH环境下的src下.
你只上传了raft的代码,没有上传你GOPATH下的labrpc,我就拿不到这个package....

**Comment by happyer** [comment]
哦，知道了，我现在已经上传了，3q
